import { useState } from 'react';
import type { RevealLeaf, RevealResponse } from '@/shared/types';
import { RevealSingle } from './RevealSingle';
import { RevealCluster } from './RevealCluster';
import { RevealInconclusive } from './RevealInconclusive';
import { RevealFeedbackFooter } from './RevealFeedbackFooter';

// "Результат готов!" only ever fit the single-winner case — showing it above
// an honest "мы не смогли определить одну профессию" message contradicted
// the message itself. Each status gets its own upfront framing instead, so
// the headline and the hedge below it agree before the child even reads it.
const HEADER_COPY: Record<RevealResponse['status'], { emoji: string; title: string }> = {
  single: { emoji: '✨', title: 'Результат готов!' },
  cluster: { emoji: '🤔', title: 'Нашли несколько вариантов' },
  inconclusive: { emoji: '🧭', title: 'Пока не нашли один точный вариант' },
};

interface RevealCardProps {
  reveal: RevealResponse;
  onRejectAll: (slugs: string[]) => void;
  onLikeLeaf: (leaf: RevealLeaf) => void;
  onFeedback: (liked: boolean, note: string | null) => void;
  onRetakeTest: () => void;
}

// Branches the reveal UI by `reveal.status`: a single confident pick (hero +
// spares) reads very differently from a cluster of 2-3 tied finalists (see
// RevealSingle / RevealCluster) or the honest "couldn't narrow it down"
// dead end (see RevealInconclusive). Copy stays hedged (reveal.message,
// generated by akinator_report_service) — never a flat "твоя профессия — X"
// claim. "🔍 Узнать, подходит ли мне" on any leaf opens the RJP simulation
// for that leaf (onLikeLeaf) instead of finishing the session here — see
// SimulationCard. Dismissing without trying only happens in bulk, via the
// footer's "none of these" (onRejectAll) — no more per-card ✕, which used to
// silently trigger the same full belief re-derivation as onRejectAll from a
// single card, often bouncing the user straight into a fresh question with
// no warning that it would do more than remove that one card.
export function RevealCard({
  reveal, onRejectAll, onLikeLeaf, onFeedback, onRetakeTest,
}: RevealCardProps) {
  const [feedbackMode, setFeedbackMode] = useState<'disliked' | null>(null);

  const topLeaf = reveal.leaves[0];
  if (reveal.status === 'single' && !topLeaf) return null;

  const slugsShown =
    reveal.status === 'single'
      ? [topLeaf.slug, ...reveal.backups.map(b => b.slug)]
      : reveal.leaves.map(l => l.slug);

  const header = HEADER_COPY[reveal.status];

  return (
    <div
      className="w-full max-w-xl bg-surface border-2 border-strong rounded-[24px] p-6 lg:p-8 flex flex-col gap-6"
      style={{ boxShadow: '0 10px 30px rgba(30,27,75,.04)' }}
    >
      <div className="text-center flex flex-col items-center gap-3">
        <span className="text-5xl select-none animate-bounce">{header.emoji}</span>
        <h2 className="font-black text-primary tracking-[-0.02em]" style={{ fontSize: 32 }}>
          {header.title}
        </h2>
        <p className="text-secondary leading-relaxed font-medium" style={{ fontSize: 16 }}>
          {reveal.message}
        </p>
      </div>

      {reveal.status === 'single' ? (
        <RevealSingle
          leaf={topLeaf}
          backups={reveal.backups}
          onLike={onLikeLeaf}
        />
      ) : reveal.status === 'cluster' ? (
        <RevealCluster
          leaves={reveal.leaves}
          strengths={reveal.strengths}
          onLike={onLikeLeaf}
        />
      ) : (
        <RevealInconclusive
          strengths={reveal.strengths}
          leaves={reveal.leaves}
          onLike={onLikeLeaf}
          onRetakeTest={onRetakeTest}
        />
      )}

      <RevealFeedbackFooter
        variant={reveal.status === 'inconclusive' ? 'final' : 'continue'}
        onContinue={() => onRejectAll(slugsShown)}
        mode={feedbackMode}
        onPickDisliked={() => setFeedbackMode('disliked')}
        onCancel={() => setFeedbackMode(null)}
        onSubmit={note => onFeedback(false, note)}
      />
    </div>
  );
}
