export const API = {
  auth: {
    me: '/auth/me',
    register: '/auth/register',
    login: '/auth/login',
    google: '/auth/google',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
    forgotPassword: '/auth/forgot-password',
    verifyResetCode: '/auth/verify-reset-code',
    resetPassword: '/auth/reset-password',
  },
  profile: {
    get: '/profile',
    create: '/profile',
    update: '/profile',
    artifacts: '/profile/artifacts',
    certificates: '/profile/certificates',
  },
  assessment: {
    start: '/assessment/start',
    current: '/assessment/current',
    questions: (assessmentId: string) => `/assessment/${assessmentId}/questions`,
    answers: (assessmentId: string) => `/assessment/${assessmentId}/answers`,
    motivationTriplets: (assessmentId: string) => `/assessment/${assessmentId}/motivation-triplets`,
    motivationAnswers: (assessmentId: string) => `/assessment/${assessmentId}/motivation-answers`,
    motivationPairs: (assessmentId: string) => `/assessment/${assessmentId}/motivation-pairs`,
    motivationPairAnswers: (assessmentId: string) => `/assessment/${assessmentId}/motivation-pair-answers`,
    pairs: (assessmentId: string) => `/assessment/${assessmentId}/pairs`,
    pairAnswers: (assessmentId: string) => `/assessment/${assessmentId}/pair-answers`,
  },
  result: {
    generate: '/result/generate',
    get: (assessmentId: string) => `/result/${assessmentId}`,
    feedback: '/result/feedback',
  },
  roadmap: {
    generate: '/roadmap/generate',
    get: (assessmentId: string) => `/roadmap/${assessmentId}`,
    generateDirection: '/roadmap/direction',
    getDirection: (assessmentId: string, slug: string) =>
      `/roadmap/${assessmentId}/directions/${slug}`,
  },
  universities: {
    programs: '/universities/programs',
    programDetail: (id: string) => `/universities/programs/${id}`,
    list: '/universities',
    countries: '/universities/countries',
    detail: (id: string) => `/universities/${id}`,
    favorite: (id: string) => `/universities/${id}/favorite`,
  },
  inquiry: {
    questions: (assessmentId: string, slug: string) =>
      `/inquiry/${assessmentId}/directions/${slug}/questions`,
    verdict: (assessmentId: string, slug: string) =>
      `/inquiry/${assessmentId}/directions/${slug}/verdict`,
  },
  admin: {
    users: '/admin/users',
    usersExport: '/admin/users/export',
    userDetail: (id: string) => `/admin/users/${id}`,
    assessmentDetail: (id: string) => `/admin/assessments/${id}`,
    assessmentExport: (id: string) => `/admin/assessments/${id}/export`,
    feedback: '/admin/feedback',
    feedbackStats: '/admin/feedback/stats',
    universities: '/admin/universities',
    universityDetail: (id: string) => `/admin/universities/${id}`,
    programDetail: (id: string) => `/admin/programs/${id}`,
    questions: '/admin/questions',
    questionDetail: (id: string) => `/admin/questions/${id}`,
    questionPairs: '/admin/question-pairs',
    questionPairDetail: (id: string) => `/admin/question-pairs/${id}`,
    motivationStatements: '/admin/motivation-statements',
    motivationStatementDetail: (id: string) => `/admin/motivation-statements/${id}`,
    motivationPairs: '/admin/motivation-pairs',
    motivationPairDetail: (id: string) => `/admin/motivation-pairs/${id}`,
    directions: '/admin/directions',
    directionDetail: (id: string) => `/admin/directions/${id}`,
  },
} as const;
